version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - '3306:3306' # ホストからゲストへポートフォワード
    environment:
      MYSQL_DATABASE: docker_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: yuki
      MYSQL_PASSWORD: password

  test-db:
      image: mysql:5.7
      ports:
        - '3307:3306' # ホストからゲストへポートフォワード
      environment:
        MYSQL_DATABASE: docker_test
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: yuki
        MYSQL_PASSWORD: password
      
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true #pry-byebugを使えるようにする
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
      - test-db
      - selenium_chrome
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/myproject:cached # ソースコード変更したらDocker側も即反映されるように

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
    logging:
      driver: none